# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac5a2b995fcc4ef9804b50ba3d323a3d19e97f15b0c9ed098744c8d0036d89f25a9976a9c8b078eb80497bc16d4a5febc4b534a6934b00677255ad307b9fa691

test:
  secret_key_base: 333f4330c02cc83a74d80960812dd4e781cdf05f2143a04cd47a176e13ce7e276326f53ef9a8092788637072a6d169b9e4fe6272392a2668a83596f363476701

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
